ACTIVATION_FUNCTION_OPTIONS = ["softmax", "relu", "sigmoid", "tanh"]
COST_FUNCTION_OPTIONS = ["mean-squared-error", "cross-entropy"]
OPTIMIZER_OPTIONS = ["gradient-descent", "rmsprop", "adam", "adagrad"]

# TODO - Setup to meet reasonably good
CONFIGS = {
    "custom": {
        "dimensions": [11, 100, 50, 6],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "mnist",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 10,
        "test_fraction": 0.1,
        "minibatch_size": 10,
        "map_batch_size": 0,
        "steps": 100,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [0, 1, 2],
        "display_biases": [0, 1, 2]
    },
    "wine": {
        "dimensions": [11, 100, 50, 6],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "wine",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "glass": {
        "dimensions": [9, 100, 50, 6],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "glass",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "yeast": {
        "dimensions": [8, 100, 50, 10],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "yeast",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "hackers-choice": {  # Iris data-set
        "dimensions": [4, 100, 50, 3],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "hackers-choice",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "mnist": {
        "dimensions": [784, 50, 10],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.001,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "mnist",
        "case_fraction": 0.1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 100,
        "map_batch_size": 0,
        "steps": 1000,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "parity": {
        "dimensions": [10, 100, 50, 2],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "parity",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "symmetry": {
        "dimensions": [101, 100, 50, 2],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "symmetry",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "one-hot-autoencoder": {
        "dimensions": [8, 100, 50, 8],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "one-hot-autoencoder",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "dense-autoencoder": {
        "dimensions": [8, 100, 50, 8],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "dense-autoencoder",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "bit-counter": {
        "dimensions": [8, 100, 50, 16],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "bit-counter",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
    "segment-counter": {
        "dimensions": [25, 100, 50, 9],
        "hidden_activation_function": "relu",
        "output_activation_function": "softmax",
        "cost_function": "mean-squared-error",
        "learning_rate": 0.0075,
        "init_weight_range": (-0.5, 0.5),
        "optimizer": "adam",
        "data_source": "segment-counter",
        "case_fraction": 1,
        "validation_fraction": 0.1,
        "validation_interval": 100,
        "test_fraction": 0.1,
        "minibatch_size": 250,
        "map_batch_size": 0,
        "steps": 2500,
        "map_layers": [],
        "map_dendrograms": [],
        "display_weights": [],
        "display_biases": []
    },
}
